Update install_lvi_mitigation_bindir script
The PR updates the script as follows.
- Support clang, clang-8, and clang-9 such that the users can now build the helloworld sample with LVI mitigation using multiple versions of clang.
- Handle ~ when specifying the installation path.

Also, fixing a bug in the helloworld sample that allows users to specify compiler with `CC=... make ...` when enabling LVI mitigation.

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

diff --git a/scripts/lvi-mitigation/invoke_compiler b/scripts/lvi-mitigation/invoke_compiler
--- a/scripts/lvi-mitigation/invoke_compiler
+++ b/scripts/lvi-mitigation/invoke_compiler
@@ -2,9 +2,14 @@
 # Copyright (c) Open Enclave SDK contributors.
 # Licensed under the MIT License.
 
-# shellcheck disable=SC2068 disable=SC2006 disable=SC2179
+# shellcheck disable=SC2068 disable=SC2006 disable=SC2179 disable=SC2154
 
-function call_clangpp {
+function call_compiler {
+    if [[ -z ${compiler+x} ]] || [[ -z ${lvi_bin_path+x} ]]; then
+        printf '%s\n' "Error: compiler or lvi_bin_path is not specified." >&2
+        exit 1
+    fi
+
     lvi_mitigation=0
     args=()
     for a; do
@@ -19,16 +24,12 @@ function call_clangpp {
     done
 
     if [ $lvi_mitigation == 0 ]; then
-        /usr/bin/clang++-7 $@
+        /usr/bin/"$compiler" $@
     else
-        # Ensures that the clang++-7 invokes customized
-        # `as` and `ld` instead of default one.
-        lvi_bin_path=$(dirname "$0")
-        clangpp_sym="$lvi_bin_path"/clang++-7_symlink
+        # Ensures that the compiler invokes customized
+        # `as` and `ld` instead of default ones.
+        compiler_sym="$lvi_bin_path"/"$compiler"_symlink
         export PATH=/bin:/usr/local:"$lvi_bin_path"
-        "$clangpp_sym" ${args[@]}
+        "$compiler_sym" ${args[@]}
     fi
 }
-
-# shellcheck disable=SC2068
-call_clangpp $@
