check-license: Improved file selection.

diff --git a/scripts/check-license b/scripts/check-license
--- a/scripts/check-license
+++ b/scripts/check-license
@@ -7,18 +7,18 @@
 ##
 ## check-license:
 ##
-##     This script checks for OpenEnclave sources that are missing the license
+##     This script checks for OpenEnclave files that are missing the license
 ##     header. It prints the names of files with missing headers to standard
 ##     output.
 ##
-##     To ignore certain sources from this check, add them to:
+##     To ignore certain files or directories, add them to:
 ##         ./scripts/.check-license.ignore
 ##
 ##==============================================================================
 
 ##==============================================================================
 ##
-## Reject any parameters.
+## Check command line arguments.
 ##
 ##==============================================================================
 
@@ -30,108 +30,123 @@ fi
 
 ##==============================================================================
 ##
-## The script must be run from the root of the openenclave source tree.
+## check_directory()
+##
+##     Check that script is running from the root of the openenclave 
+##     distribution.
 ##
 ##==============================================================================
 
-bn=`basename ${PWD}`
-
-if [ "${bn}" != "openenclave" ]; then
-    echo "$0: please run from root of openenclave source tree"
-    exit 1
-fi
-
-##==============================================================================
-##
-## Form the list of files to ignore from the test below.
-##
-##==============================================================================
-
-ignorefile="./scripts/.check-license.ignore"
-
-if [ ! -f "${ignorefile}" ]; then
-    echo "$0: missing file: ${ignorefile}"
-    exit 1
-fi
-
-ignorelist=`cat ${ignorefile}`
-
-##==============================================================================
-##
-## Form the list of files to include from the test below.
-##
-##==============================================================================
-
-includefile="./scripts/.check-license.include"
-
-if [ ! -f "${includefile}" ]; then
-    echo "$0: missing file: ${includefile}"
-    exit 1
-fi
-
-##==============================================================================
-##
-## Form the list of all OpenEnclave files.
-##
-##==============================================================================
-
-files=`/bin/mktemp`
-
-find . -name '*.h' >> ${files}
-find . -name '*.c' >> ${files}
-find . -name '*.cpp' >> ${files}
-find . -name '*.asm' >> ${files}
-find . -name '*.S' >> ${files}
-find . -name '*.conf' >> ${files}
-find . -name '*.idl' >> ${files}
-find . -name '*.inc' >> ${files}
-find . -name '*.cmake' >> ${files}
-find . -name 'CMakeLists.txt' >> ${files}
-find . -name 'Makefile' >> ${files}
-find . -name '*.make' >> ${files}
-find . -name '*.py' >> ${files}
-grep '#[ \t]*!.*bash' -r -l . >> ${files}
-
-# Append include file to files:
-cat ${includefile} >> ${files}
-
-tmpfile=`/bin/mktemp`
-
-# Remove lines that match entries from ignore file:
-for i in ${ignorelist}
-do
-    cp ${files} ${tmpfile}
-    fgrep -v ${i} ${tmpfile} > ${files}
-done
-
-fileslist=`cat ${files}`
-
-rm -f ${tmpfile}
-
-##==============================================================================
-##
-## Verify that ${fileslist} was properly formed (check that each file exists)
-##
-##==============================================================================
-
-for i in ${fileslist}
-do 
-    if [ ! -f "${i}" ]; then
-        echo "$0: file not found: ${i}"
+check_directory()
+{
+    if [ "`basename ${PWD}`" != "openenclave" ]; then
+        echo "$0: please run from root of openenclave source tree"
         exit 1
     fi
-done
+}
+
+check_directory
 
 ##==============================================================================
 ##
-## Find files that are not included but that have Microsoft license:
+## expand_ignore_file():
+##
+##     Expand any wildcards in the .check-license.ignore file:
 ##
 ##==============================================================================
 
-function check_not_included()
+expand_ignore_file()
+{
+    local filename="./scripts/.check-license.ignore"
+    local tempfile=`/bin/mktemp`
+
+    # Fail if ignore file does not exist:
+    if [ ! -f "${filename}" ]; then
+        echo "$0: missing file: ${filename}"
+        exit 1
+    fi
+
+    # Expand each entry in the ignore file:
+    set -f
+    for i in `cat ${filename}`
+    do
+        if [ -e "${i}" ]; then
+            echo ${i} >> ${tempfile}
+        else
+            bn=`basename ${i}`
+            if [ "${bn}" == "${i}" ]; then
+                find . -name "${bn}" >> ${tempfile}
+            else
+                set +f
+                echo ${i} >> ${tempfile}
+                set -f
+            fi
+        fi
+    done
+    set +f
+
+    echo ${tempfile}
+}
+
+ignorefile=`expand_ignore_file`
+
+##==============================================================================
+##
+## form_filelist(ignorefile):
+##
+##     Form the list of files by finding all regular files and then removing
+##     ignore files.
+##
+##==============================================================================
+
+form_filelist()
+{
+    local ignorefile=$1
+    local files=`/bin/mktemp`
+    local tmpfile=`/bin/mktemp`
+
+    # Find all regular files:
+    find . -type f >> ${files}
+
+    # Remove lines that match entries from ignore file:
+    for i in `cat ${ignorefile}`
+    do
+        cp ${files} ${tmpfile}
+        fgrep -v ${i} ${tmpfile} > ${files}
+    done
+
+    filelist=`cat ${files}`
+
+    rm -f ${files}
+    rm -f ${tmpfile}
+
+    # Sanity check: make sure all files in list exist:
+    for i in ${filelist}
+    do 
+        if [ ! -f "${i}" ]; then
+            echo "$0: file not found: ${i}"
+            exit 1
+        fi
+    done
+
+    echo ${filelist}
+}
+
+filelist=`form_filelist ${ignorefile}`
+rm -rf ${ignorefile}
+
+##==============================================================================
+##
+## check_not_included():
+##
+##     Find files that are not included but that have Microsoft license.
+##
+##==============================================================================
+
+check_not_included()
 {
     tmpfile1=`/bin/mktemp`
-    ls ${fileslist} | sed 's/^..//g' | sort >> ${tmpfile1}
+    ls ${filelist} | sed 's/^..//g' | sort >> ${tmpfile1}
 
     tmpfile2=`/bin/mktemp`
     grep -r -l 'Copyright (c) Microsoft Corporation' | sort >> ${tmpfile2}
@@ -139,7 +154,8 @@ function check_not_included()
     echo diff ${tmpfile1} ${tmpfile2}
     diff ${tmpfile1} ${tmpfile2}
 
-    exit
+    rm -f ${tmpfile1}
+    rm -f ${tmpfile2}
 }
 
 ##==============================================================================
@@ -157,38 +173,41 @@ EOF
 
 ##==============================================================================
 ##
-## Check each openenclave source file for the license.
+## check_for_missing_license_headers(filelist, license)
+##
+##     Check each OpenEnclave files that are missing the license header.
 ##
 ##==============================================================================
 
-tmpfile=`/bin/mktemp`
+function check_for_missing_license_headers()
+{
+    local filelist="$1"
+    local license="$2"
+    local tmpfile=`/bin/mktemp`
+    local ret=0
 
-success=0
+    for i in ${filelist}
+    do
+        # Grep for first 'Copyright' line (-m1)
+        # Print the following line too (-A1)
+        # Use SED to strip leading '//' or leading '#':
+        grep -m1 -A1 "Copyright (c) Microsoft Corporation" ${i} | \
+        sed 's~// ~~g' | \
+        sed 's~;; ~~g' | \
+        sed 's~^# ~~g' \
+        > ${tmpfile}
 
-for i in ${fileslist}
-do
-    # Grep for first 'Copyright' line (-m1)
-    # Print the following line too (-A1)
-    # Use SED to strip leading '//' or leading '#':
-    grep -m1 -A1 "Copyright (c) Microsoft Corporation" ${i} | \
-    sed 's~// ~~g' | \
-    sed 's~;; ~~g' | \
-    sed 's~^# ~~g' \
-    > ${tmpfile}
+        # Diff matching file with expected license text:
+        diff -w ${tmpfile} ${license} > /dev/null 2> /dev/null
+        if [ "$?" != "0" ]; then
+            echo ${i}
+            ret=1
+        fi
+    done
 
-    # Diff matching file with expected license text:
-    diff -w ${tmpfile} ${license} > /dev/null 2> /dev/null
-    if [ "$?" != "0" ]; then
-        echo ${i}
-        success=1
-    fi
-done
+    rm -rf ${tmpfile}
 
-##==============================================================================
-##
-## Cleanup temporary files and print exit
-##
-##==============================================================================
+    return ${ret}
+}
 
-rm -f ${tmpfile} ${license} ${files}
-exit ${success}
+check_for_missing_license_headers "${filelist}" "${license}"
