Added tool to detect whether SGX is present in build system and run SGX tests if so. Else just run simulated tests.

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -144,6 +144,12 @@ if [ ! -x "${BINDIR}/oeelf" ]; then
     exit 1
 fi
 
+cp bin/oesgx ${BINDIR}
+if [ ! -x "${BINDIR}/oesgx" ]; then
+    echo "$0: failed to install ${OE_BINDIR}/oesgx"
+    exit 1
+fi
+
 echo "Created ${BINDIR}"
 
 ##==============================================================================
