New sample for getting started guide

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -138,6 +138,12 @@ if [ ! -x "${BINDIR}/oegen" ]; then
     exit 1
 fi
 
+cp bin/oeelf ${BINDIR}
+if [ ! -x "${BINDIR}/oeelf" ]; then
+    echo "$0: failed to install ${OE_BINDIR}/oeelf"
+    exit 1
+fi
+
 echo "Created ${BINDIR}"
 
 ##==============================================================================
